In [2]:
import numpy as np

In [17]:
X = np.array([[1, 2], [3, 4], [10, 11], [12, 13]], dtype=np.float64)
W = np.array([[3, 4, 7], [5, 6, 8]], dtype=np.float64)
y = np.array([0, 1, 2, 1], dtype=np.int64)
print(X)
print(W)
print(y)



[[ 1.  2.]
 [ 3.  4.]
 [10. 11.]
 [12. 13.]]
[[3. 4. 7.]
 [5. 6. 8.]]
[0 1 2 1]


In [27]:
loss = 0.0
dW = np.zeros_like(W)

for i in range (X.shape[0]):
    scores = X[i].dot(W)
    scores = np.exp(scores)
    sum = 0
    for j in range(W.shape[1]):
        sum += scores[j]
    loss += -np.log(scores[y[i]]) + np.log(sum)

    dW[:, y[i]] -= X[i]
    for j in range(W.shape[1]):
        dW[:, j] += ((1/sum) * (scores[j])) * X[i]



loss /= X.shape[0]
dW /= float(X.shape[0])

# loss += reg * np.sum(W * W)
# dW += 2 * reg * W

print(loss)
print(dW)

22.250239216357585
[[-0.24998866 -3.74977222  3.99976088]
 [-0.49997732 -4.24954445  4.74952178]]


In [34]:
loss = 0.0
dW = np.zeros_like(W)
scores = X @ W
scoresEXP = np.exp(scores)
sums = np.sum(scoresEXP, axis=1)
correct = scoresEXP[np.arange(len(y)), y]
correct_log = -np.log(correct)
sums_log = np.log(sums)
loss += np.sum(correct_log + sums_log)
loss /= X.shape[0]
# loss += reg * np.sum(W * W)

dloss = 1
dloss /= X.shape[0]
dcorrect_log = dloss * np.ones(X.shape[0])
dsums_log = dloss * np.ones(X.shape[0])

dcorrect = (-1/correct)  * dcorrect_log
dsums = (1/sums) * dsums_log

dscoresEXP = np.zeros((X.shape[0], W.shape[1]))
dscoresEXP[np.arange(len(y)), y] += dcorrect
dscoresEXP = (np.ones_like(dscoresEXP) * dsums[:, np.newaxis]) + dscoresEXP


dscores = scoresEXP * dscoresEXP
dW = X.T @ dscores





print(loss)
print(dW)

22.250239216357585
[[-0.24998866 -3.74977222  3.99976088]
 [-0.49997732 -4.24954445  4.74952178]]


In [81]:
dW = np.zeros(W.shape)
y=[0, 1]

loss = 0.0
for i in range(2):
    scores = X[i].dot(W)
    correct_class_score = scores[y[i]]
    for j in range(3):
        if j == y[i]:
            continue
        margin = scores[j] - correct_class_score + 1
        if margin > 0:
            loss += margin
            dW[:, j] += X[i]
            dW[:, y[i]] -= X[i]
        print(margin)
loss /= 2
dW /= 2

loss, dW

3.9000000000000004
10.9
-5.699999999999999
18.0


(16.4,
 array([[-1., -1.,  2.],
        [-2., -1.,  3.]]))

In [99]:
scores= X @ W
print(scores)
np.argmax(scores, axis=1)

[[13.1 16.  23. ]
 [29.3 36.  53. ]]


array([2, 2])